name: SafeFly
version: 2.1
main: me.chocolf.safefly.SafeFly
api-version: 1.13
authors: [ Chocolf ]
description: Disable certain things like PvP and the use of certain Items whilst flying
commands:
  safefly:
    description: Toggles SafeFly for player
    permission: SafeFly.use
    usage: "Usage: /<command> <Player> [On/Off]"
    aliases: [sfly]
  safeflyreload:
    description: Reloads SafeFly config
    permission: SafeFly.reload
    usage: "Usage: /<command>"
    aliases: [sflyreload]
  safeflyspeed:
    description: Sets fly speed for player.
    permission: SafeFly.speed
    usage: "Usage: /<command> <Speed> [Player]"
    aliases: [sflyspeed]
  safeflytimer:
    description: Toggles SafeFly for player for certain amount of time.
    permission: SafeFly.timer
    usage: "Usage: /<command> <Duration in Seconds> [Player]"
    aliases: [sflytimer]